### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by h-2** [decke/redports#3]
I used the old redports and was very pleased to see that there now is a new platform!

I have forked freebsd/freebsd-ports: https://github.com/h-2/freebsd-ports
I went to redports.org and gave the redports app access to my github, then activated redports on the above repo.
Then I created a branch with a new port and pushed that to github: https://github.com/h-2/freebsd-ports/tree/new/unigine_valley

Shouldn't something happen now? I also tried creating a PR from the new branch into the master branch to see if that would trigger anything (like travis), but so far I couldn't find anything :o

Thanks for your help!

**Comment by decke** [comment]
The new redports codebase is still under heavy development. The biggest missing items right now are the Github integration for status updates (which is what gives you feedback about job status, error logs ...) and the poudriere backend integration which builds the jobs (half of it is done so far).

I could see that some build jobs were actually created for your repository but they are waiting in the queue for a builder now. Please stay tuned.
